name = "deepseek-graphql-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 定义环境变量（用于存储API密钥）
[vars]
# 这里不要填写实际的API密钥，仅作为示例
API_KEY = ""

# 配置环境
[env.production]
# 生产环境专用配置
workers_dev = true

[env.development]
# 开发环境专用配置
workers_dev = true

[dev]
port = 8787
local_protocol = "http"
